### ISSUE TITLE
When I use docker this doesn't seem to work

### ISSUE THREAD

**Issue by redfort1987** [doutv/Auto-GPT-Notion#7]
Hi again, I wanted to run Auto-GPT through docker and now I'm running into the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/app/autogpt/plugins.py", line 219, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
  File "<frozen zipimport>", line 302, in load_module
  File "plugins/Auto-GPT-Notion-master.zip/Auto-GPT-Notion-master/src/notion/__init__.py", line 8, in <module>
ModuleNotFoundError: No module named 'notion_client'

It seems that when using docker it can't find the module.

**Comment by doutv** [comment]
I haven't tried run it in Docker. 
You may need to add the following command to Dockerfile 
```
pip install notion-client python-dotenv auto_gpt_plugin_template
```
Or, add `notion-client python-dotenv auto_gpt_plugin_template` them to `requirements.txt`

**Comment by Losspost** [comment]
> I haven't tried run it in Docker. You may need to add the following command to Dockerfile
> 
> ```
> pip install notion-client python-dotenv auto_gpt_plugin_template
> ```
> 
> Or, add `notion-client python-dotenv auto_gpt_plugin_template` them to `requirements.txt`

Adding it to the requirements.txt AND rebuild the docker worked for me.
